### ISSUE TITLE
Consider replace relabeling with `attach_node_metadata`

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/observability#103]
This [PR just got merged upstream](https://github.com/prometheus/prometheus/pull/10080), which changes Prometheus Kubernetes Service discovery to optionally include node labels to metrics provided by pods. This option simplifies a lot of [relabeling configuration](https://github.com/gitpod-io/observability/blob/8ba92d90169b72815d433492ddc50c756829b968/addons/metrics-relabeling.libsonnet#L52-L130) that we currently maintain and also some nasty joins we do on Grafana[[1](https://github.com/gitpod-io/gitpod/blob/f3a621b0af171eab483afeefd0c5b2117e3a658c/operations/observability/mixins/cross-teams/dashboards/gitpod-nodes-overview.libsonnet#L169-L173)][[2](https://github.com/gitpod-io/gitpod/blob/f3a621b0af171eab483afeefd0c5b2117e3a658c/operations/observability/mixins/cross-teams/dashboards/gitpod-nodes-overview.libsonnet#L221-L223)] just so we can correlate a pod with the node where it is running.

It is quite far for us to use this still, a new Prometheus version needs to be released, a new version of Prometheus-operator also needs to be released with support for this, but I'm already opening this issue and putting it on our backlog so we don't forget to analyze it in the future

**Comment by mads-hartmann** [comment]
Moving this to the reducing technical debt epic.

**Comment by ArthurSens** [comment]
This change doesn't add value, it has been open for too long with close to 0 discussion since then. I'm closing to remove it from our radar
