### ISSUE TITLE
Flaky test: Scraping metrics from Kubescape

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/observability#109]
Our e2e tests are flaky when it comes to scraping metrics from kubescape. E.g. https://github.com/gitpod-io/observability/runs/5964858522?check_suite_focus=true

We should understand why that is happening and fix it

**Comment by meysholdt** [comment]
Happend [here](https://gitpod.slack.com/archives/C032A46PWR0/p1651128838146539?thread_ts=1651115643.753649&cid=C032A46PWR0).

@ArthurSens, can you share your thoughts on this? If there is no easy solution, can we disable the flaky test until we found a solution?

**Comment by ArthurSens** [comment]
The flaky test is making sure Prometheus is able to scrape metrics from Kubescape. We do that by querying Prometheus for a metric that we know that it comes from Kubescape.

I suspect the flakiness comes from scrape timing. Kubescape is intentionally scraped less often because we don't need to scan our clusters every 15s for vulnerabilities. Maybe we're timing out too early, and Prometheus still hasn't scraped Kubescape yet.

It is just a thought tho, I haven't looked deep into it.

---

Obviously, the preferred option would be to fix the flaky test, but if we don't have time for that at the moment I'd prefer to unmark this test as a "Required" on the Pull Request protection. That way we still the test for all pull requests, but we don't block merge on failures

**Comment by ArthurSens** [comment]
Looks like #159 didn't solve it 🙁

**Comment by ArthurSens** [comment]
Flaky test solved by removing it 😆 

https://github.com/gitpod-io/observability/pull/278
