### ISSUE TITLE
Improve tools to investigate certificate expiration

### ISSUE THREAD

**Issue by wulfthimm** [gitpod-io/observability#20]
The [current dashboard](https://grafana.gitpod.io/d/TvuRo2iMk/cert-manager?orgId=1&refresh=1m) for diagnosing certificate issues is degraded as not all certificates are shown because certificates with the same name and namespace are merged and shown as one certificate. To be able to find the certifcate which caused the alert we need specific information where the certificate is also in the dashboard.

**Comment by ArthurSens** [comment]
The dashboard is developed upstream. I'd suggest opening a Pull Request to https://gitlab.com/uneeq-oss/cert-manager-mixin with the changes you'd like to see 🙂

**Comment by wulfthimm** [comment]
That does not make sense in this context as the dashboard is good for a single cluster but we merge all data.

**Comment by ArthurSens** [comment]
Exactly, this can be changed! We just need to propose a Pull Request. The idea was already accepted upstream, we just need to implement it. See also: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/issues/5

**Comment by wulfthimm** [comment]
Thanks! What might be the best variable to do that, the certmanager exports an instance value which contains the IP address. Is there a convention for exporting the clustername? Would it be best practice to join it with another metric?
