### ISSUE TITLE
components/otel-collector: Make it production-ready!

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/observability#22]
Currently, we only run it inside our preview environments. To make it ready for production usage, there is a couple of things we want to add:

- [ ] #26

- [ ] #27
- [ ] #28

**Comment by mads-hartmann** [comment]
Closing this in favour of having smaller issues tracked in the Honeycomb epic in our [new board](https://github.com/orgs/gitpod-io/projects/23/views/1)
