### ISSUE TITLE
Configure the otel-collector to send traces to both Jaeger and Honeycomb

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/observability#26]
To provide backward compatibility with what we currently have, we want our otel-collector to keep sending traces to Jaeger while also sending them to Honeycomb. We need to modify the otel-collector accordingly.

**Comment by mads-hartmann** [comment]
@ArthurSens Changed the scope of this so it is only for staging initially.

**Comment by ArthurSens** [comment]
This repository in particular has no knowledge of any existing environment. So the context here doesn't really care if it's staging/prod/preview who is going to send traces to Honeycomb or Jaeger.

What we need to do is add the possibility to configure this, our ArgoCD apps that consume this repository are the ones deciding if traces go to Honeycomb or Jaeger 🙂

**Comment by mads-hartmann** [comment]
@ArthurSens That makes sense, I have changed the title and will create a new issue for enabling tracing in staging and configuring gitpod to send traces to the otel-collector.
