### ISSUE TITLE
monitoring-central/jsonnet: Duplicate certificate resources

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/observability#294]
We're currently deploying duplicate certificates for Grafana and VictoriaMetrics. This is a problem especially when they are battling for ownership of their secret and one of those certificates is misconfigured.

Since when creating an Ingress we already create a certificate, we should deploy a separate certificate to it.

**Comment by ArthurSens** [comment]
It is also arguable that we're already migrating monitoring-central to Go as well and we don't need to bother with jsonnet bugs 🤷

**Comment by meysholdt** [comment]
@ArthurSens Can you check if we ported the bug to Go? 
I assume that we did because our strategy was to achieve YAML parity.

**Comment by meysholdt** [comment]
This came up [here again](https://gitpod.slack.com/archives/C03MWBB5MP1/p1661975959747099?thread_ts=1661970409.958919&cid=C03MWBB5MP1).

**Comment by ArthurSens** [comment]
> @ArthurSens Can you check if we ported the bug to Go?
> I assume that we did because our strategy was to achieve YAML parity.

We never migrated monitoring-central to go, so the bug was not backported 🙂 

The bug is not causing any real issues, besides the creation of a resource that does nothing. Since we're moving away from jsonnet for monitoring-central too so we can just leave this undone 😅
