### ISSUE TITLE
Add GCP support for monitoring central and monitoring-satellite

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/observability#31]
## Is your feature request related to a problem? Please describe
As part of the Meta team's [first steps into automatic deployment](https://github.com/gitpod-io/gitpod/issues/6785), we need to improve our monitoring and observability.
Unfortunately some metrics are currently only available in GCP, such as [database CPU utilization](https://console.cloud.google.com/monitoring/dashboards/resourceList/cloudsql_database?project=gitpod-191109).
Therefore we would like to have GCP support for monitoring satellite.

## Describe the behaviour you'd like
To be able to use metrics from GCP in Grafana. 

## Additional context
[Slack](https://gitpod.slack.com/archives/C01KGM9EBD4/p1637671960425400)

**Comment by mads-hartmann** [comment]
I'm scheduling this ticket for now. @ArthurSens and @meysholdt I don't have a sense of how much work this is and what the solution space looks like. Would one of you be able to spell that out for me so we can more easily prioritise this.

**Comment by meysholdt** [comment]
I think the solution is to add GCP Monitoring (aka Stackdriver) as a Datasource in Grafana. We had that in the past and therefore there are probably code snippets in our git history on how to do that. 

With that in place, we can use [MQL](https://cloud.google.com/monitoring/mql) to add queries / graphs to grafana.

There is one caveat though: In preview environments, the data will most likely represent the whole GCP project and not an individual preview env. Thus we should only use this for data that prometheus does not have: metrics about managed MySQL, bucket storage, etc.

**Comment by mads-hartmann** [comment]
@ArthurSens Is this still blocked? :)

**Comment by mads-hartmann** [comment]
@ArthurSens Reopening as we still have to update the monitoring satellite installations to configure the new data source right? :)

**Comment by ArthurSens** [comment]
Yes, that's true. I just closed this one because they are kind of different tasks... I'll modify the ArgoCD apps and close this again though, no problems

**Comment by ArthurSens** [comment]
All set!

Stackdriver datasource is present for preview envs, staging and production :)
