### ISSUE TITLE
Broken release pipeline

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/observability#327]
In https://github.com/gitpod-io/observability/pull/319 we tried to create a pipeline responsible for creating new releases everytime the source code of the installer changed.

We just merged https://github.com/gitpod-io/observability/pull/323, so a new release should have been created.

What we observed instead was that the semver of the [new release was not incremented](https://github.com/gitpod-io/observability/actions/runs/3106357974), and the result was that the preview release got the assets updated instead.

We should make sure that new releases are created instead of updating assets from old ones.

**Comment by Siddhant-K-code** [comment]
this is the default behavior of `softprops/action-gh-release` see [this comment](https://github.com/softprops/action-gh-release/issues/45#issuecomment-894743076)

**Comment by Siddhant-K-code** [comment]
`paulhatch/semantic-version` action is creating the minor version also, that's the version it is not getting bumped.

see this [[1]](https://github.com/gitpod-io/observability/actions/runs/3106357974/jobs/5033133550#step:3:15), [[2]](https://github.com/gitpod-io/observability/actions/runs/3103162419/jobs/5026189835#step:3:15)


And, Since we are using the same `version` output in publishing the GitHub Action release, it is updating the existing assets.

**Comment by Siddhant-K-code** [comment]
Final Workflow should look like this:

```diff
name: Release
on:
  push:
    branches:
      - main

env:
  golang-version: "1.19"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        # https://github.com/PaulHatch/semantic-version
      - id: semver
        uses: paulhatch/semantic-version@v4
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
-         # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
-         minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
+         format: "${major}${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "installer/"
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: false
      - uses: actions/setup-go@v2
        if: ${{steps.semver.outputs.changed}}
        with:
          go-version: ${{ env.golang-version }}
      - name: Build artifacts
        if: ${{steps.semver.outputs.changed}}
        run: VERSION=${{steps.semver.outputs.version_tag}} ./hack/build-obs-installer.sh
        # https://github.com/softprops/action-gh-release
      - uses: softprops/action-gh-release@v1
        if: ${{steps.semver.outputs.changed}}
        with:
          tag_name: ${{steps.semver.outputs.version_tag}}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: ./installer/*.tar.gz

```

if you want, I can create the PR for same^

**Comment by ArthurSens** [comment]
👋 -- Thanks for taking a look at this :) 

Yes, it would be awesome if you could create a PR fixing the pipeline :)

One question, where does this `${increment}` comes from in the comment above?

**Comment by Siddhant-K-code** [comment]
Sure, I will raise the PR.

> One question, where does this `${increment}` comes from in the comment above?

It was already there (see [here](https://github.com/gitpod-io/observability/blob/main/.github/workflows/release.yaml#L29)) - It is provided in [official docs](https://github.com/PaulHatch/semantic-version#:~:text=for%20this%20commit-,increment,-is%20an%20additional). I think we can remove that also.

**Comment by Siddhant-K-code** [comment]
if https://github.com/gitpod-io/observability/pull/332 doesn't work, maybe we need to use different gh-release-action that will not update existing assets.
