### ISSUE TITLE
Add OTC to monitoring satellite deployment

### ISSUE THREAD

**Issue by liam-j-bennett** [gitpod-io/observability#371]
## Summary
In order to simplify configuration and allow upstream changes to be deployed easier. We need to deploy OTC with each monitoring-satellite deployment. This allows us to configure upstream stores and local sampling from a single location, rather than from each service using tracing. 

The OTC deployment should point to the upstream monitoring-central OTC and also be configured with authentication required by the upstream components.

This work is dependent on the upstream OTC work https://github.com/gitpod-io/observability/issues/372

## Checklist
- Add upstream charts to monitoring-satellite
- Add configuration options for upstream address and authentication secrets
- Test configuration with `tracegen` (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/tracegen)

**Comment by ArthurSens** [comment]
It is deployed already 🤔

**Comment by liam-j-bennett** [comment]
> It is deployed already 🤔, but the current configuration only allows us to send traces to Honeycomb. We just need to expand the config to be able to send to other destinations as well

Does it have the necessary configuration options?

**Comment by ArthurSens** [comment]
> > It is deployed already 🤔, but the current configuration only allows us to send traces to Honeycomb. We just need to expand the config to be able to send to other destinations as well
> 
> Does it have the necessary configuration options?

That's what I meant, we need to extend the go code to allow this config 😅
