### ISSUE TITLE
Ensure that all installations of observability reference a fixed git SHA

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/observability#39]
Due to our usage of extVars we currently often introduce backwards incompatible changes. This is a problem as we have many places where our observability installations refer to the `main` branch.

To make sure we don't break installations unintentionally we should fix the git SHA for all installations for now so that updates becomes intentional. 

Meanwhile we'll work on finding to make it easier to evolve our jsonnet programs without introducing breaking changes all the time in this ticket https://github.com/gitpod-io/observability/issues/34

The following places needs to have their git SHA fixed

1. ArgoCD applications in gitpod-io/ops ([example](https://github.com/gitpod-io/ops/blob/620fcc6faf441935219f18ac2f43bb5247609289/deploy/io-dev/argocd/monitoring-satellite.yaml#L49))
2. The workspace monitoring satellite deploy script [here](https://github.com/gitpod-io/ops/blob/main/deploy/workspace/monitoring-satellite.sh)
3. Preview environments deploys ([here](https://github.com/gitpod-io/gitpod/blob/main/.werft/observability/monitoring-satellite.ts#L27))

We should also extend the README with information on how to "deploy" monitoring satellite now that we have a fixed SHA:

**Comment by ArthurSens** [comment]
As it might sound super simple, there is one thing that makes this process a little bit more complex than expected 😬 (Worry not! A solution was already thought and implemented upstream)

Gitpod dashboards and alerts are developed in another repository and are imported to the vendor folder in this repository [through automation](https://github.com/gitpod-io/observability/blob/main/.github/workflows/dep-update.yaml). 

If we simply update all downstream projects to a fixed commit SHA, we'll need to update everything every time a dashboard or alert changes as well, pointing to the new commit SHA.

---

Inspired by kube-prometheus [release process](https://github.com/prometheus-operator/kube-prometheus/blob/main/RELEASE.md), we could have something like this:

* We maintain a separate branch for each minor release, named release-<major>.<minor>, e.g. release-0.1, release-0.2
* The CI workflow is modified to [open PRs updating dependencies to `main` and to other release branches](https://github.com/gitpod-io/observability/blob/11c09226cffbafb46e08f23e7654641802ae4ce4/.github/workflows/dep-update.yaml#L10-L13).
* Downstream should pin to the release branch.
* We can introduce as many breaking changes as we'd like to main, but will need to cut a new release (with changelog) everytime an engineering team wants to use any new feature

**Comment by mads-hartmann** [comment]
@ArthurSens Ah damn, moving back to the inbox and have marked it as Pending clarification until we have decided on a specific way forward.

**Comment by meysholdt** [comment]
let's keep the time during which there is a version-pinning short because during that time product teams can not ship changes to monitoring.

**Comment by mads-hartmann** [comment]
Closing this issue as we fixed this as part of making the jsonnet programs backwards compatible (we fixed the git sha temporarily before while rolling out the new backwards-compatible version)
