### ISSUE TITLE
`Dep update` Github Action fails on `Update jsonnet dependencies`

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/observability#417]
### Bug description

[Here](https://github.com/gitpod-io/observability/actions/runs/3808363709/jobs/6478881151#step:4:69) is a sample job run that is failing

### Steps to reproduce

Run the job (I ran it three times and they all failed)

Interestingly, [the same steps](https://github.com/gitpod-io/observability/blob/e15d2eab8cbd7d461e7b4f967e4123b3e1daed80/.github/workflows/dep-update.yaml#L23-L29) pass from within a Gitpod workspace.

### Expected behavior

It would ideally pass

### Anything else?

It runs successfully from a Gitpod workspace. :thinking: Perhaps it is related to Github Action runner changes? [Ref](https://github.com/gitpod-io/observability/pull/404)

**Comment by kylos101** [comment]
> the CI fails because it ends with exit code 1 if there is nothing to update. I'm running the script manually inside a workspace and I can see that nothing is being updated, besides the jsonnetfile.lock.json file.

Can you echo a message on failure, so folks know why the job failed? This way they get feedback from the job, without having to troubleshoot it in a workspace.

> Are you sure that the PRs making changes to dashboards were merged before you triggered the CI here?

I recall trying to run this to update SLOs in Pyrra. Perhaps this is the wrong workflow? I was not trying to update a dashboard...doh! What workflow updates Pyrra? Sorry...

**Comment by ArthurSens** [comment]
> > the CI fails because it ends with exit code 1 if there is nothing to update. I'm running the script manually inside a workspace and I can see that nothing is being updated, besides the jsonnetfile.lock.json file.
> 
> Can you echo a message on failure, so folks know why the job failed? This way they get feedback from the job, without having to troubleshoot it in a workspace.

That's a very good idea! Let me open a PR

 
> > Are you sure that the PRs making changes to dashboards were merged before you triggered the CI here?
> 
> I recall trying to run this to update SLOs in Pyrra. Perhaps this is the wrong workflow? I was not trying to update a dashboard...doh! What workflow updates Pyrra? Sorry...

SLOs are managed by ArgoCD, e.g. the [workspace-slos app](https://argo-cd.gitpod-io-dev.com/applications/workspace-slos?resource=). We tried to document that in the [architecture page](https://www.notion.so/gitpod/Service-Level-Objectives-9702597ce8874920ae5be7cb665fce26#2282be1c8b33464a96fcdeda13914dec) 🙂

**Comment by kylos101** [comment]
Thank you for clarifying how SLOs ship!
