### ISSUE TITLE
Grafana dashboard unable to correctly determine the node count

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/observability#44]
### Bug description

The grafana dashboard should show correct count of node per node pool created by k3s cluster. The K3s cluster is not being managed by google.

![image](https://user-images.githubusercontent.com/32481722/144812007-95e25486-11bf-43ca-b714-2fd4600f453a.png)

### Steps to reproduce

Navigate to the dashboard and check under Cluster size section

### Expected behavior

The right number of nodes along with node pool name should be shown. Ex. the meta cluster which is gke has right node pool names and counts 
![image](https://user-images.githubusercontent.com/32481722/144812097-a84b7398-5136-442c-937a-b0871c9c87b4.png)

### Anything else?

I believe [this comment](https://github.com/gitpod-io/runbooks/issues/197#issuecomment-882277279) on the issue was not addressed.

**Comment by mads-hartmann** [comment]
@princerachit is this bug still an issue? I see eu25 and us25 showing up in the [Cross Teams / Gitpod / Overview](https://grafana.gitpod.io/d/gitpod-overview/gitpod-overview?orgId=1&refresh=30s) dashboard but I don't if that is the current k3s clusters ☺️

**Comment by princerachit** [comment]
We have used a workaround of adding gke specific labels to k3s cluster. I don't mind closing this issue.
