### ISSUE TITLE
with-observability not deploying in core-dev due to pod security policy

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/observability#52]
### Bug description

The `prometheus-k8s` stateful set is being prevented from scheduling pods due to Pod Security Policy in core-dev. As a result, I am unable to deploy `with-helm` and `with-observability` to test observability changes.

`kubectl describe statefulset prometheus-k8s` reveals:
```shell
Events:
  Type     Reason        Age                  From                    Message
  ----     ------        ----                 ----                    -------
  Warning  FailedCreate  12m (x23 over 100m)  statefulset-controller  create Pod prometheus-k8s-0 in StatefulSet prometheus-k8s failed error: pods "prometheus-k8s-0" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[1]: Invalid value: "projected": projected volumes are not allowed to be used]
```

This command waits up to an hour, and then the werft job times out:
`kubectl rollout status statefulset prometheus-k8s`

`alertmanager-main` is also experiencing a similar issue, but, I don't see a `kubectl rollout status` check for it that would cause this issue.

```shell
kubectl get statefulset
NAME                READY   AGE
alertmanager-main   0/1     97m
prometheus-k8s      0/1     97m
```

### Steps to reproduce

1. Build a new preview environment with the installer
2. Run `werft run github -a with-observability=true -a with-helm=true`, this should also trigger a with clean slate deployment, because your going from Installer to Helm.
3. The build should never finish and eventually timeout, not actually deploying Gitpod to the preview environment.

### Expected behavior

The pod security policy should pass, and the deploy should continue.

### Example repository

[branch](https://github.com/gitpod-io/gitpod/tree/refs/heads/kyleb/ws-dashboard)
[build](https://werft.gitpod-dev.com/job/gitpod-build-kyleb-ws-dashboard.3)

### Anything else?

As a workaround, I manually edited the pod security policy causing this trouble. Therefore, it's possible you won't be able to recreate this issue, unless you regenerate the related pod security policy.

**Comment by kylos101** [comment]
As a workaround, I am going to try doing two builds:

```
werft run github -a with-clean-slate-deployment=true -a with-helm=true
werft run github -a with-clean-slate-deployment=true -a with-helm=true -a with-observabilityi=true
```

**Comment by kylos101** [comment]
As a workaround, I added the `projected` volume via `kubectl edit podsecuritypolicy kube-prometheus-restricted`, which is a cluster scoped pod security policy in core-dev . 

I'm not quite sure how jsonnet is being used to generate and manage k8s manifests, but the core issue is - this file `monitoring-satellite/manifests/podsecuritypolicy-restricted.yaml` doesn't appear to get applied on `kubectl apply`.

**Comment by kylos101** [comment]
[With this workaround](https://github.com/gitpod-io/observability/issues/52#issuecomment-999818695), I am able to get Grafana and Prometheus running, so I can inspect my dashboard changes.

However, it looks like [Grafana](https://grafana-kyleb-ws-dashboard.preview.gitpod-dev.com/dashboards) and [Prometheus](https://prometheus-kyleb-ws-dashboard.preview.gitpod-dev.com/graph) are not available given the [werft URLS](https://werft.gitpod-dev.com/job/gitpod-build-kyleb-ws-dashboard.13/results), even though the pods are running. Troubleshooting continues!

**Comment by mads-hartmann** [comment]
Scheduling this /cc @meysholdt

**Comment by ArthurSens** [comment]
The fix was proposed upstream, once it's merged we only need to update our dependencies again :)

https://github.com/prometheus-operator/kube-prometheus/pull/1572

**Comment by mads-hartmann** [comment]
@ArthurSens Oh nice, thanks for fixing it upstream! I'll put this to In progress and assign it to you so you can close it once the PR is merged and we've updated our dependencies ☺️

**Comment by kylos101** [comment]
Yeah, great solution! 👍👍

When we test, we should be sure to remove the change I made in core-dev.
This way it uses this upstream change too.

**Comment by ArthurSens** [comment]
What is interesting here is how we were able to spin up the pods in our CI. We probably need to make sure our CI cluster respects pod security policies

**Comment by kylos101** [comment]
> What is interesting here is how we were able to spin up the pods in our CI. We probably need to make sure our CI cluster respects pod security policies

@ArthurSens By CI, are you referring werft deploying to `core-dev`, or werft deploying to new k3s stuffs?

For `core-dev`, as a workaround, [I did a workaround by editing the PodSecurityPolicy](https://github.com/gitpod-io/observability/issues/52#issuecomment-999818695) to permit projected volumes. In hindsight, that was a bad decision, as production likely didn't support projected volumes either - leading to the Prometheus outage @meysholdt found.

Now that we have this upstream change, we should check the related pod security policy, `kube-prometheus-restricted`, to ensure it was updated (instead of continuing to have my workaround). Let me know if you want to talk? I had a hard time understanding jsonnet, and how those changes make it to Kubernetes.

**Comment by ArthurSens** [comment]
I mean this repository's CI. This repository doesn't really "care" about core-dev as it is just one of its consumers.

We have a github action that deploys monitoring-satellite into a KinD cluster and make a couple of HTTP requests to prometheus API to make sure it is running smoothly. (See our [CI definition](https://github.com/gitpod-io/observability/blob/main/.github/workflows/ci.yaml) and [e2e tests](https://github.com/gitpod-io/observability/blob/main/tests/e2e/main_test.go)).

I would expect that our CI would fail if prometheus's pod doesn't come up due to lack of permission in the pod security policy.
