### ISSUE TITLE
The ability to explore HTTP error codes (similar to gRPC errors) in Honeycomb

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/observability#53]
Hi, I'm just looking to start a conversation, this may not be the correct repo. 

It would be ideal if we could explore HTTP error codes (similar to how we can do with gPRC) in Honeycomb. [Here is an example.](https://ui.honeycomb.io/gitpod/datasets/gitpod-production/result/xpNnGTE1W3M)

Also here, in case it gets archived (the purple spike is image-builder-mk3 throwing):
![image](https://user-images.githubusercontent.com/1272076/147007985-bbc34bdf-7dcb-4339-8c15-24c7bf903bbb.png)

Is it a common use case, to visualize HTTP errors in Honeycomb? If it is possible, what might be needed from the product teams to help make this a reality?

Why are we asking? We experienced [an incident earlier today](https://app.incident.io/incidents/89) where it would have been helpful. Without this capability, and with Grafana being temporarily offline (until we increased its lmits) we had to identify impacted components, search GCP, and search related logs.

**Comment by kylos101** [comment]
This would be ideal for list, create, and start workspace actions. There's likely other actions too, this is just an example.

**Comment by mads-hartmann** [comment]
Hey @kylos101 👋  adding attributes with HTTP status codes is definitely a very common use-case and they are extremely useful ☺️ I've extended our [Telemetry documentation](https://www.notion.so/gitpod/Naming-conventions-af9084c4743349089cf2450a3c860733#728cfadaf6524f62a0a77bebbc1f232f) to link the the [OpenTelemetry Semantic conventions for HTTP spans](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md) as those are the conventions we should follow. But you're right now, currently we haven't instrumented our services to add HTTP attributes to spans related to HTTP operations.

I'll close this issue though as it is up to the teams to implement the required instrumentation to add those attributes ☺️ I suggest reaching out to the relevant teams and see if you they're interested in improving their HTTP-related instrumentation.
