### ISSUE TITLE
Review the limits on the Grafana pod

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/observability#54]
### Bug description

May we ask @gitpod-io/platform to review the limits on the Grafana pod? 

We had an issue today, where the Gitpod Overview dashboard was missing data for about 20 minutes. Upon further examination we found the Grafana pod was crash looping and needed more resources. This was solved by increasing its limits, so that the pod could start and serve the dashboard again (so that we could consume Victoria Metrics).

[Please refer to the incident for a complete timeline.](https://app.incident.io/incidents/89) As you can see, after this issue happened, we had a separate issue where images could not be pulled, which prevented some users from starting workspaces.

### Steps to reproduce

n/a

### Expected behavior

The Grafana pod would not crash loop due to resource constraints, within reason of course. :)

### Example repository

n/a

### Anything else?

[Also related to the same incident.](https://github.com/gitpod-io/observability/issues/53)

**Comment by mads-hartmann** [comment]
@meysholdt I'm scheduling this ☺️
