### ISSUE TITLE
Job monitoring/jaeger-spark-dependencies fails often, triggers a warning, and lacks a runbook

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/observability#55]
**Update 04.01.22 by Mads**: See this [comment](https://github.com/gitpod-io/observability/issues/55#issuecomment-1004624144) for a suggestion on how to fix this.

### Bug description

We get this alert in the warning channel many times a day for both meta clusters, and monitoring central.

```
[FIRING] prod-meta-us01 Monitoring
**Please take a look when possible**
Cluster: prod-meta-us01
Alert: KubeJobFailed
Description: Job monitoring/jaeger-spark-dependencies-1640130900 failed to complete. Removing failed job after investigation should clear this alert.
```

The job appears to be failing because of this error related to missing database grants, but I'm not sure which database is in question.

> Error
> 2021-12-22T00:00:55.838263131ZException in thread "main" com.datastax.driver.core.exceptions.UnauthorizedException: User jaeger has no SELECT permission on <table system.size_estimates> or any of its parents at com.datastax.driver.core.exceptions.UnauthorizedException.copy(UnauthorizedException.java:59) at com.datastax.driver.core.exceptions.UnauthorizedException.copy(UnauthorizedException.java:25) at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245) at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68) at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:51) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.datastax.spark.connector.cql.SessionProxy.invoke(SessionProxy.scala:37) at com.sun.proxy.$Proxy17.execute(Unknown Source) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.datastax.spark.connector.cql.SessionProxy.invoke(SessionProxy.scala:37) at com.sun.proxy.$Proxy18.execute(Unknown Source) at com.datastax.spark.connector.rdd.partitioner.DataSizeEstimates$$anonfun$tokenRanges$1.apply(DataSizeEstimates.scala:40) at com.datastax.spark.connector.rdd.partitioner.DataSizeEstimates$$anonfun$tokenRanges$1.apply(DataSizeEstimates.scala:38) at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:112) at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:111) at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:145) at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111) at com.datastax.spark.connector.rdd.partitioner.DataSizeEstimates.tokenRanges$lzycompute(DataSizeEstimates.scala:38) at com.datastax.spark.connector.rdd.partitioner.DataSizeEstimates.tokenRanges(DataSizeEstimates.scala:37) at com.datastax.spark.connector.rdd.partitioner.DataSizeEstimates.totalDataSizeInBytes$lzycompute(DataSizeEstimates.scala:88) at com.datastax.spark.connector.rdd.partitioner.DataSizeEstimates.totalDataSizeInBytes(DataSizeEstimates.scala:87) at com.datastax.spark.connector.rdd.partitioner.DataSizeEstimates.dataSizeInBytes$lzycompute(DataSizeEstimates.scala:81) at com.datastax.spark.connector.rdd.partitioner.DataSizeEstimates.dataSizeInBytes(DataSizeEstimates.scala:80) at com.datastax.spark.connector.rdd.partitioner.SplitSizeEstimator$class.estimateDataSize(SplitSizeEstimator.scala:12) at com.datastax.spark.connector.rdd.partitioner.SplitSizeEstimator$class.estimateSplitCount(SplitSizeEstimator.scala:21) at com.datastax.spark.connector.rdd.CassandraTableScanRDD.estimateSplitCount(CassandraTableScanRDD.scala:62) at com.datastax.spark.connector.rdd.CassandraTableScanRDD$$anonfun$1.apply$mcI$sp(CassandraTableScanRDD.scala:226) at com.datastax.spark.connector.rdd.CassandraTableScanRDD$$anonfun$1.apply(CassandraTableScanRDD.scala:226) at com.datastax.spark.connector.rdd.CassandraTableScanRDD$$anonfun$1.apply(CassandraTableScanRDD.scala:226) at scala.Option.getOrElse(Option.scala:121) at com.datastax.spark.connector.rdd.CassandraTableScanRDD.partitionGenerator$lzycompute(CassandraTableScanRDD.scala:226) at com.datastax.spark.connector.rdd.CassandraTableScanRDD.partitionGenerator(CassandraTableScanRDD.scala:222) at com.datastax.spark.connector.rdd.CassandraTableScanRDD.getPartitions(CassandraTableScanRDD.scala:271) at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253) at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251) at scala.Option.getOrElse(Option.scala:121) at org.apache.spark.rdd.RDD.partitions(RDD.scala:251) at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35) at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253) at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251) at scala.Option.getOrElse(Option.scala:121) at org.apache.spark.rdd.RDD.partitions(RDD.scala:251) at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35) at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253) at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251) at scala.Option.getOrElse(Option.scala:121) at org.apache.spark.rdd.RDD.partitions(RDD.scala:251) at org.apache.spark.Partitioner$$anonfun$4.apply(Partitioner.scala:75) at org.apache.spark.Partitioner$$anonfun$4.apply(Partitioner.scala:75) at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) at scala.collection.immutable.List.foreach(List.scala:381) at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) at scala.collection.immutable.List.map(List.scala:285) at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:75) at org.apache.spark.rdd.PairRDDFunctions$$anonfun$groupByKey$3.apply(PairRDDFunctions.scala:641) at org.apache.spark.rdd.PairRDDFunctions$$anonfun$groupByKey$3.apply(PairRDDFunctions.scala:641) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112) at org.apache.spark.rdd.RDD.withScope(RDD.scala:363) at org.apache.spark.rdd.PairRDDFunctions.groupByKey(PairRDDFunctions.scala:640) at org.apache.spark.api.java.JavaPairRDD.groupByKey(JavaPairRDD.scala:559) at io.jaegertracing.spark.dependencies.cassandra.CassandraDependenciesJob.run(CassandraDependenciesJob.java:169) at io.jaegertracing.spark.dependencies.DependenciesSparkJob.run(DependenciesSparkJob.java:60) at io.jaegertracing.spark.dependencies.DependenciesSparkJob.main(DependenciesSparkJob.java:40) Caused by: com.datastax.driver.core.exceptions.UnauthorizedException: User jaeger has no SELECT permission on <table system.size_estimates> or any of its parents at com.datastax.driver.core.Responses$Error.asException(Responses.java:134) at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179) at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:177) at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:46) at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:799) at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:633) at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070) at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993) at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:801) at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) at java.lang.Thread.run(Thread.java:748)

### Steps to reproduce

Search the warning channel for `monitoring/jaeger-spark-dependencies`

### Expected behavior

Options:
1. [Add a related runbook here](https://github.com/gitpod-io/runbooks/blob/main/runbooks/KubeJobFailed.md), assuming the alert and job are both needed
2. Delete the alert if it is not needed
3. Delete the alert and job because neither are needed

### Example repository

n/a

### Anything else?

Taking action on this will add value regardless of which path we choose.

Adding a runbook means the alert and job are both meaningful, and we'll know what its for, and how to fix it.

Removing the alert reduces noise (overhead) in our warning channel, making the warning channel more useful to on-call staff.

Removing the alert and job (because neither are needed) reduces the amount we have to support overall.

**Comment by mads-hartmann** [comment]
@kylos101 Thanks for creating the bug! As we want to get rid of Jaeger I'd don't want to spend as little time as possible on this. @ArthurSens do you know if it is possible to configure the KubeJobFailed alert to ignore specific jobs? If so I'd like to have it just ignore the jaeger related jobs for now.

**Comment by ArthurSens** [comment]
Well, the job description literally tells us what to do to fix it. I'm not sure why we haven't deleted that job yet.

Last time I checked they were almost an year old

**Comment by mads-hartmann** [comment]
The current failing job in prod-meta-us01 is only 12 hours old, so I'm assuming that if we delete the job the next one will just fail and retrigger the alert ☺️

I'd rather not spend time fixing the underlying issues (fixing the DB permissions) so I'd prefer to just have `KubeJobFailed`ignore the job if possible.

**Comment by mads-hartmann** [comment]
I'll schedule this, we should be able to ignore it using modifying the [inhibit_rule](https://prometheus.io/docs/alerting/latest/configuration/#inhibit_rule)s we in our alertmanager config [here](https://github.com/gitpod-io/observability/blob/main/addons/alerting.libsonnet#L70).

Here are all the labels that we can use to target this kind of alert (screenshot of the Alertmanager for the alert)

<img width="1242" alt="screenshot" src="https://user-images.githubusercontent.com/83561/148033011-a9cfd7df-6b27-47f8-ae38-2ddad5394a81.png">

**Comment by kylos101** [comment]
Thank you, @mads-hartmann ! Can we also include [this alert](https://gitpod.slack.com/archives/C01TNS9FCQ3/p1642791316060600)? It's for `jaeger-collector` and has been noisy lately, too.

I ask because we're planning to set Slack Notifications for the warning channel, to explore using it to be proactive, and it'd be nice to remove the Jaeger noise.

**Comment by mads-hartmann** [comment]
@kylos101 We're scheduling work this week to get rid of Jaeger completely in all our environments - these alerts should go away once https://github.com/gitpod-io/ops/issues/829 is done. I'll close this issue and leave a link to it in the other issue to verify that the alerts no longer happen.
