### ISSUE TITLE
Trouble accessing preview environment URLs for Grafana and Prometheus

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/observability#56]
### Bug description

This [werft build](https://werft.gitpod-dev.com/job/gitpod-build-kyleb-ws-dashboard.13/results) shares a couple URLs for [Grafana](https://grafana-kyleb-ws-dashboard.preview.gitpod-dev.com/dashboards) and [Prometheus](https://prometheus-kyleb-ws-dashboard.preview.gitpod-dev.com/graph). I get this for both:
```
This site can’t be reachedprometheus-kyleb-ws-dashboard.preview.gitpod-dev.com unexpectedly closed the connection.
```

As a workaround, I am using `kubectl port-forward`:
`kubectl port-forward svc/grafana 3000:3000`

### Steps to reproduce

1. Build a new preview environment using the installer.
2. Then, in a 2nd build, clean the slate and use helm, `werft run github -a with-clean-slate-deployment=true -a with-helm=true`
3. Then in a 3rd build, layer on observability and use a custom observability branch, if needed, `werft run github -a with-observability=true -a withObservabilityBranch=kyleb/fixes-52`

### Expected behavior

The URLs provided by the werft job at end of a successful build for step 3 should work, or they should be removed altogether, and users should be expected to port-forward. The former is probably a better solution, this way folks don't have to learn how to do k8s port forwarding.

### Example repository

n/a

### Anything else?

Happy to help, lemme know if there are any questions? Thank you very much for your support, Platform Team!

**Comment by kylos101** [comment]
It looks like the ingress are unable to find the related secrets.

> Warning  Sync    5m26s (x35 over 3h49m)  loadbalancer-controller  Error syncing to GCP: error running load balancer syncing routine: error initializing translator env: secrets "grafana-certificate" not found

>Warning  Sync    7m (x28 over 3h51m)  loadbalancer-controller  Error syncing to GCP: error running load balancer syncing routine: error initializing translator env: secrets "prometheus-certificate" not found

**Comment by kylos101** [comment]
As a heads up, when this issue happens, it delays the deploy up to 15m, which isn't ideal from a "tight dev loop" standpoint. 

Instead, it might be better to fail sooner (15m seems like a long time) and output a message indicating a workaround like `kubectl port-forward svc/grafana 3000:3000`.

**Comment by mads-hartmann** [comment]
Scheduling this /cc @meysholdt

**Comment by mads-hartmann** [comment]
Note to self, I followed the steps above to reproduce (with the modification of using `with-helm` in step 3 as well) and can confirm the URLs don't work. I'm heading out the door but will look more tomorrow. ([job 1](https://werft.gitpod-dev.com/job/gitpod-build-mads-testing-o11y.1), [job 2](https://werft.gitpod-dev.com/job/gitpod-build-mads-testing-o11y.2), [job 3](https://werft.gitpod-dev.com/job/gitpod-build-mads-testing-o11y.3))

**Comment by mads-hartmann** [comment]
@ArthurSens Assigned this to you as per our discussion ☺️
