### ISSUE TITLE
Improve approval and merge for dep-update workflow

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/observability#59]
Hey there,

While working [this PR](https://github.com/gitpod-io/observability/pull/58), I bumped into this observation and wanted to share some suggestions.

Observation:
When the [dep-update workflow](https://github.com/gitpod-io/observability/blob/main/.github/workflows/dep-update.yaml#L42) is run, it assigns @ArthurSens as an approver to the PR.

May I suggest:
1. Add @gitpod-io/platform to this repo and set it as the reviewer when this workflow is run. This way, everyone on the platform team can find related PRs using a common filter.
2. [If the PR was created by this workflow](https://github.com/gitpod-io/observability/blob/main/.github/workflows/dep-update.yaml), passes all checks, and doesn't include a blocking label (like a hold), automatically merge the PR.

Questions:
1. Are there any scenarios where you'd want to have the PR created, but not auto merge?

**Comment by mads-hartmann** [comment]
@kylos101 Thanks! I'll open a PR to assign reviews to the platform team as you suggest. I won't prioritise auto-merging yet, but postpone that work until it becomes a burden for the platform team to review the PRs ☺️
