### ISSUE TITLE
Fix and Re-Apply automated Updated

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/observability#60]
I've just [reverted](https://github.com/gitpod-io/observability/commit/823581fcb47c694a2206733226a1ec7af66294c6) Update https://github.com/gitpod-io/observability/commit/56ea3a7cad6058b8aa4a2b4bcb1d320d32e967a1 because it broke Prometheus on the meta clusters. The Prometheus pods were no longer starting via an error message 

> create Pod prometheus-k8s-0 in StatefulSet prometheus-k8s failed error: pods "prometheus-k8s-0" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[1]: invalid value: "projected": projected volumes are not allowed to be used] ".

Du to the error, we do not have monitoring data for the meta clusters from 2022-01-01 18:51 to 2022-01-02 10:07 UTC.

**Comment by mads-hartmann** [comment]
The error messages sounds related to https://github.com/gitpod-io/observability/issues/52

**Comment by meysholdt** [comment]
yes, seems to be the same.
