### ISSUE TITLE
Alert "TargetDown" ?

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/observability#67]
We see the Alert "TargetDown" firing with severity "warning". 

Unfortunately, the [message from the definition](https://github.com/prometheus-operator/kube-prometheus/blob/5f13d381556c1b93ed7ea4dc09c1c4cc84be72b5/manifests/kube-prometheus-prometheusRule.yaml#L18) is missing in the slack notification, so I can't quite understand what the alert is telling me. 

Is it possible to have the message in Slack?

**Comment by ArthurSens** [comment]
It will be fixed here: https://github.com/prometheus-operator/kube-prometheus/pull/1093

**Comment by ArthurSens** [comment]
It got merged!
