### ISSUE TITLE
Automatically approve and merge dependency update PRs

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/observability#67]
(Description updated by Mads 24-01-2022 to match the implementation we decided on)

We want our [dependency update PRs](https://github.com/gitpod-io/observability/blob/main/.github/workflows/dep-update.yaml) to be reviewed and merged automatically. 

- Change the GitHub Workflow to also approve the PR automatically. We should follow the same pattern as in the ops repository, so the PR should be created by gitpod-gitops-bot and approved by roboquat (see [here](https://github.com/gitpod-io/ops/blob/main/.werft/deploy/github.ts))
- Add the observability repository to Prow to it follows same rules at gitpod-io/ops (see [here](https://github.com/gitpod-io/gitbot/blob/main/config/config.yaml#L65))

**Comment by mads-hartmann** [comment]
@ArthurSens How do you feel about us just adding observability to Prow as well and have the PRs be automatically approved by our bots and merged once CI checks pass, same way we do with the automated deployments in gitpod-io/ops?

**Comment by ArthurSens** [comment]
All good from my side!

**Comment by mads-hartmann** [comment]
Updated issue description and title to match our preferred solution.
