### ISSUE TITLE
Add grafana dashboard for CoreDNS monitoring

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/observability#75]
Grafana dashboard that would monitor our k8s's coredns deployments.
Something like this one: https://grafana.com/grafana/dashboards/12382
We can then setup alerts for when coredns is under heavy load or experiencing failures.

**Comment by kylos101** [comment]
Thank you, @sagor999, I appreciate you creating this issue ! 

May I ask a favor? Can you close this issue, and add its contents to [#7829](https://github.com/gitpod-io/gitpod/issues/7826)? We generally create alerts and dashboards in the `gitpod` repo. 

[It'll make sense once you read this doc on how we do observability at Gitpod.](https://github.com/gitpod-io/gitpod/tree/main/operations/observability/mixins)
