### ISSUE TITLE
Also see in slack the messages that we receive in PagerDuty

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/observability#85]
I received https://gitpod.pagerduty.com/incidents/PW7HTYO in PagerDuty, which was great!

However, there was noting on our "critical" channel. It would be great if either PagerDuty or AlertManager/Prometheus could deliver the alert to that channel, too.

**Comment by meysholdt** [comment]
Maybe it's better when PagerDuty delivers the Slack Message, because 
* we can see all needed details in PD (runbooks etc), so the concern that I voiced in the past has been invalidated.
* there is integration: https://support.pagerduty.com/docs/slack-integration-guide

**Comment by ArthurSens** [comment]
I've merged a dirty fix for this, but I just found a better solution: https://www.robustperception.io/sending-alert-notifications-to-multiple-destinations

I'll open a new PR based on that example ☝️

**Comment by ArthurSens** [comment]
Reopening since this approach is not what we want. We want pager duty to send a message to slack so we can "acknowledge"
