### ISSUE TITLE
New security constraints coming to Prometheus-Operator

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/observability#98]
Prometheus-operator just got a [new release](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.55.0) with several new security policies implemented:

- [CHANGE] Enabled read-only root filesystem for containers generated from the Prometheus, Alertmanager and ThanosRuler objects. https://github.com/prometheus-operator/prometheus-operator/pull/4552
- [CHANGE] Disabled privilege escalation for the containers generated from Prometheus, Alertmanager and ThanosRuler objects. https://github.com/prometheus-operator/prometheus-operator/pull/4552
- [CHANGE] Dropped all capabilities for the containers generated from Prometheus, Alertmanager and ThanosRuler objects. https://github.com/prometheus-operator/prometheus-operator/pull/4552
- [CHANGE] Added emptyDir volume to the Prometheus statefulset when spec.queryLogFile is only a base filename (e.g. query.log as opposed to /tmp/query.log). When the path contains a full path, a volume + volume mount should be explicitly given in the Prometheus spec since the root file system is now read-only. https://github.com/prometheus-operator/prometheus-operator/pull/4566

All those changes will be imported here by our next Automated version update, we should keep an eye on when that happens and make sure everything is working as expected.

**Comment by mads-hartmann** [comment]
@ArthurSens Added this to the next iteration, but if we're lucky this is no-op for us right?

**Comment by ArthurSens** [comment]
> @ArthurSens Added this to the next iteration, but if we're lucky this is no-op for us right?

Hopefully yes 🤞

**Comment by ArthurSens** [comment]
Those changes are live and nothing seems to be broken!
